### ISSUE TITLE
gfx906 support

### ISSUE THREAD

**Issue by IMbackK** [ROCm/composable_kernel#1020]
While building this i noticed that gfx906 has been removed from the list of gpu targets, this seams premature considering gfx906 is still otherwise supported

**Comment by zjing14** [comment]
Which Operators you are using? You can try `-D GPU_TARGETS="gfx906"` and `-D DL_KERNELS=on` in Cmake.

**Comment by IMbackK** [comment]
sure that still works, but the default build dose not build for gfx906 anymore since
https://github.com/ROCm/composable_kernel/commit/59dbb01fd11e869ff69705f959a0871475858282
which is concerning since that would appear to mean gfx906 gets no testing anymore, which is opposed to the commitment made by amd to continue support until end of 2024

**Comment by illsilin** [comment]
I had to remove the gfx906 from the default targets list, because when the library is built for all the targets on that list the size of the ckProfiler binary and the library started exceeding the limits and caused the builds to fail. We have since split the library up into several pieces and build the profiler separately for separate targets, but the gfx906 will likely never return to the list, since we will soon be adding other new architectures. Also, we never really had any gfx906 hardware for our CI, so never really did any testing on gfx906.
