### ISSUE TITLE
[Issue]: tile_distribution_encoding.hpp parameters explaination

### ISSUE THREAD

**Issue by demonsan** [ROCm/composable_kernel#1693]
### Problem Description

It is hard to figure out the template parameters here. RsLengths_, HsLengthss_, Ps2RHssMajor_, Ps2RHssMinor_, Ys2RHsMajor_, Ys2RHsMinor_. Need a Readme for this to explain the meaning and how they are transformed.

### Operating System

Ubuntu22.04 LTS

### CPU

AMD Ryzen9 5900X

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.0.0

**Comment by ppanchad-amd** [comment]
Hi @demonsan. Internal ticket has been created to assist with your issue. Thanks!

**Comment by demonsan** [comment]
From tile_distribution, i found some comments. It seems R means replication, H means hidden, P means partition. I'm tring to figure out Y dimension meanning and how they are composed together. It will be really helpful if an example illustrating the mechnasim of tile_distribution can be provided. thx :)

**Comment by schung-amd** [comment]
Hi @demonsan, unfortunately we don't have any guidance prepared for external users about many aspects of CK at the moment, including this. If you have specific questions I can pass them to the internal team and see if there are straightforward answers.

**Comment by demonsan** [comment]
All right :(  I will have a try to see if i can figure out.

**Comment by schung-amd** [comment]
Sorry about that, I understand that this is quite opaque. I'm hoping we'll have better guidance prepared for CK in the future (and am pushing internally for this wherever possible), because there are a lot of aspects users have expressed interest in and we've thus far been unable to provide the level of support they need.

If it helps, I believe this section of the code is related to a tile/block view of a tensor. The idea is that each thread can be assigned a group of nearby elements for operations like matrix multiplication, so it is useful to have a representation that reflects this. Of course, I'm as in the dark as you are at the moment as to what these parameters specifically mean, but hopefully enough squinting at the source code will provide the answers.
