### ISSUE TITLE
3D forward  grouped convolution missed some instances of datatype fp32 for layout (NDHWGC, GKZYXC, NDHWGK) 

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#814]
I have integrated 3d forward group convolution kernel into miopen. However, the test cases only worked for fp16 datatype. Some test cases showed that no instances found for fp32 datatype. For example, the following test case only passed for fp16:
// g    n   c   d    h   w   k   z  y  x pad_x pad_y pad_z stri_x stri_y stri_z dia_x dia_y dia_z
   {32, 128, 32, 28, 28, 28, 32, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1}

**Comment by zjing14** [comment]
@bartekxk Please take a look.

**Comment by bartekxk** [comment]
Hello @iq136boy this case is not supported because input and output is too large.
We use GEMM for Conv so our input matrix is MxN where M = N *D * H * W and K = Z * Y * X * C

Calculation for f32 for input:
N * D * H* W * Z * Y * X * C * sizeof(float) = 128 *28 * 28 *28 *32 * 3 * 3 * 3 * 4 = 9710862336 B
9710862336 B / (1024 * 1024 * 1024) = aprox  9 GB which is not supported because we use index_t for indexing which is int32_t. Due to this, we have limitation that each tensor must be less or equan than 2GB. 
I don't how it is possible that fp16 works. Can I ask for some logs? Fp16 also doesn't work for me what is expected.

**Comment by iq136boy** [comment]
> Hello @iq136boy this case is not supported because input and output is too large. We use GEMM for Conv so our input matrix is MxN where M = N *D * H * W and K = Z * Y * X * C
> 
> Calculation for f32 for input: N * D * H* W * Z * Y * X * C * sizeof(float) = 128 *28 * 28 *28 *32 * 3 * 3 * 3 * 4 = 9710862336 B 9710862336 B / (1024 * 1024 * 1024) = aprox 9 GB which is not supported because we use index_t for indexing which is int32_t. Due to this, we have limitation that each tensor must be less or equan than 2GB. I don't how it is possible that fp16 works. Can I ask for some logs? Fp16 also doesn't work for me what is expected.

Hi @bartekxk,  thanks for the explanation. The size N * D * H* W * Z * Y * X * C * sizeof(float) is the whole size of the image of MIOpen side. When passing it to CK kernels, the channel is C1= C/G = 32/32 = 1. So for fp32, the size of each group should be 128 *28 * 28 *28 *1 * 3 * 3 * 3 * 4 = aprox 0.3 GB. I think this should be fine for CK?

**Comment by bartekxk** [comment]
Hi @iq136boy , sorry for late response. Yes, with C equal to 1 it should be fine for CK. I will investigate what is going wrong and go back with some feedback.
